name: golang_ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: go-vet-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18beta2
        uses: actions/setup-go@v1
        with:
          go-version: 1.18beta2
      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key:  golang_ci_modules
          restore-keys: golang_ci_modules
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Configure for go modules
        run: |
          git config --global url."https://git:${{ secrets.MODE_COMMON_GITHUB_TOKEN }}@github.com/moderepo".insteadOf "https://github.com/moderepo"

      - name: Get dependencies
        run: |
          go generate ./...
          go get -v -t -d ./...

      - name: apdu
        run: |
          go vet ./internal/apdu/...
          go test ./internal/apdu/...

      - name: npdu
        run: |
          go vet ./internal/npdu/...
          go test ./internal/npdu/...

      - name: transport
        run: |
          go vet ./pkg/transport/...
          go test ./pkg/transport/...
